name: glados checkin

on:
  push:
    branches: [main,master]
  schedule:
    - cron: '5 1 * * *'
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'clone repo'
        uses: actions/checkout@v3.3.0
      - name: 'run script'
        run: echo "RESULT=$(python3 ./glados_check.py)" >> $GITHUB_ENV
      - name: 'send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: glados签到 ${{env.RESULT}}
          body: 签到(${{env.RESULT}})
          to: ${{secrets.MAIL_TO}}
          from: ${{env.RESULT}}
          # content_type: text/html
